obj-$(CONFIG_SENSORS_L3G4200D_POLL)	+= l3g4200d_poll.o
obj-$(CONFIG_SENSORS_LIS3DH_ACC)        += lis3dh_acc.o
obj-$(CONFIG_SENSORS_LPS331AP)		+= lps331ap.o
obj-$(CONFIG_SENSORS_LSM303_MAG)	+= lsm303dlhc_compass.o
